name: Build Maven app on self hosted VM

on:
  push:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile with Maven
      run: mvn compile --file pom.xml
    - name: Test with Maven
      run: mvn test --file pom.xml
    - name: Build with Maven
      run: mvn install --file pom.xml
    
